# Generated by Django 4.2.2 on 2023-08-25 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('pdv', models.IntegerField(primary_key=True, serialize=False)),
                ('idregion', models.IntegerField()),
                ('idciudad', models.IntegerField()),
                ('canal', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analytics_app.store')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('retention_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analytics_app.store')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_analytics_app.store')),
            ],
        ),
    ]
